build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        tests:
            environment:
                docker: true
            dependencies:
                override:
                    - true
                before:
                    - docker-compose up -d
                    - docker exec -it build_laravel_1 sudo pecl install xdebug-2.9.4
                    - docker exec -it build_laravel_1 docker-php-ext-enable xdebug
                    - docker exec -it build_laravel_1 php artisan migrate --seed || echo 'weird'
            tests:
                override:
                    -
                        command: 'docker exec -it build_laravel_1 vendor/bin/phpunit --coverage-clover=clover'
                        coverage:
                            file: 'clover'
                            format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true

