build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        tests:
            environment:
                docker: true
            dependencies:
                before:
                    - sudo apt-get install -y pyflakes iverilog
                    - npm i -g yarn
                    - docker-compose ups
                    - docker exec -it hatchery_laravel_1 php artisan migrate --seed
                    - docker exec -it hatchery_laravel_1 yarn build
            tests:
                override:
                    -
                        command: 'docker exec -it hatchery_laravel_1 vendor/bin/phpunit --coverage-clover=clover'
                        coverage:
                            file: 'clover'
                            format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true

