language: php

php:
  - 7.1
  - 7.2

env:
  - TRAVIS_NODE_VERSION="7"

addons:
  apt:
    packages:
      - pyflakes

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --dev --no-interaction
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - yarn
  - yarn production
  - php artisan key:generate
  - php artisan config:clear
  - curl -s -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz
  - tar xvf zlib-1.2.11.tar.gz

script:
  - cd zlib-1.2.11
  - ./configure
  - echo -e "#define MAX_WBITS  13\n$(cat zconf.h)" > zconf.h
  - make
  - export PATH=$PATH:`pwd`
  - cd ..
  - vendor/bin/phpunit
  - yarn lint

after_script:
  - ./codeclimate.sh
  - php vendor/bin/codacycoverage clover build/logs/clover.xml 
