version: '3'

services:
  web:
    depends_on:
      - db
    tty: true
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: badgeware
      DB_USERNAME: badgeware
      DB_PASSWORD: badgeware

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: badgeware
      MYSQL_USER: badgeware
      MYSQL_PASSWORD: badgeware