# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
<<<<<<< HEAD
      - image: circleci/php:7.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
=======
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ROOT_PASSWORD=

    steps:
      - checkout
      - run: cp .env.testing .env

      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo apt-get install mariadb-client pyflakes
>>>>>>> master

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
<<<<<<< HEAD

      - run: composer install -n --prefer-dist

=======
      - run: composer install -n --prefer-dist
>>>>>>> master
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

<<<<<<< HEAD
      # prepare the database
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
=======
      # Build frontend
      - run: yarn build

      # prepare the database
      - run: mysqladmin create badgeware_test --user="root" --host="127.0.0.1"
      - run: php artisan key:generate --env=testing
      - run: php artisan migrate --env=testing --database=testing --force --seed
      - run: php artisan config:cache --env=testing

      # run tests with codecept
>>>>>>> master
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
