name: Laravel

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Linux packages
      run: sudo apt update && sudo apt install -y --no-install-recommends pyflakes
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Create Database
      run: mysql -uroot -proot -e 'create database badge'
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
        yarn
        yarn build
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_DATABASE: badge
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_TEST_DATABASE: badge
        DB_TEST_USERNAME: root
        DB_TEST_PASSWORD: root
      run: vendor/bin/phpunit
